// Code generated by MockGen. DO NOT EDIT.
// Source: example.com/dana/module/product/internal/usecase (interfaces: ListingUsecase)
//
// Generated by this command:
//
//	mockgen -destination=mock/listing_usecase.go -package=mock example.com/dana/module/product/internal/usecase ListingUsecase
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "example.com/dana/module/product/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockListingUsecase is a mock of ListingUsecase interface.
type MockListingUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockListingUsecaseMockRecorder
	isgomock struct{}
}

// MockListingUsecaseMockRecorder is the mock recorder for MockListingUsecase.
type MockListingUsecaseMockRecorder struct {
	mock *MockListingUsecase
}

// NewMockListingUsecase creates a new mock instance.
func NewMockListingUsecase(ctrl *gomock.Controller) *MockListingUsecase {
	mock := &MockListingUsecase{ctrl: ctrl}
	mock.recorder = &MockListingUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListingUsecase) EXPECT() *MockListingUsecaseMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockListingUsecase) GetByID(ctx context.Context, id string) (entity.Listing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.Listing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockListingUsecaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockListingUsecase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockListingUsecase) List(ctx context.Context) ([]entity.Listing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Listing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockListingUsecaseMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockListingUsecase)(nil).List), ctx)
}
