// Code generated by MockGen. DO NOT EDIT.
// Source: example.com/dana/module/product/internal/usecase (interfaces: PropertyUsecase)
//
// Generated by this command:
//
//	mockgen -destination=mock/property_usecase.go -package=mock example.com/dana/module/product/internal/usecase PropertyUsecase
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "example.com/dana/module/product/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPropertyUsecase is a mock of PropertyUsecase interface.
type MockPropertyUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockPropertyUsecaseMockRecorder
	isgomock struct{}
}

// MockPropertyUsecaseMockRecorder is the mock recorder for MockPropertyUsecase.
type MockPropertyUsecaseMockRecorder struct {
	mock *MockPropertyUsecase
}

// NewMockPropertyUsecase creates a new mock instance.
func NewMockPropertyUsecase(ctrl *gomock.Controller) *MockPropertyUsecase {
	mock := &MockPropertyUsecase{ctrl: ctrl}
	mock.recorder = &MockPropertyUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPropertyUsecase) EXPECT() *MockPropertyUsecaseMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockPropertyUsecase) GetByID(ctx context.Context, id string) (entity.Property, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.Property)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPropertyUsecaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPropertyUsecase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockPropertyUsecase) List(ctx context.Context, payload entity.ListPayload) ([]entity.Property, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, payload)
	ret0, _ := ret[0].([]entity.Property)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPropertyUsecaseMockRecorder) List(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPropertyUsecase)(nil).List), ctx, payload)
}
