// Code generated by MockGen. DO NOT EDIT.
// Source: example.com/dana/module/product/internal/repository (interfaces: ListingRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/listing_repository.go -package=mock example.com/dana/module/product/internal/repository ListingRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "example.com/dana/module/product/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockListingRepository is a mock of ListingRepository interface.
type MockListingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockListingRepositoryMockRecorder
	isgomock struct{}
}

// MockListingRepositoryMockRecorder is the mock recorder for MockListingRepository.
type MockListingRepositoryMockRecorder struct {
	mock *MockListingRepository
}

// NewMockListingRepository creates a new mock instance.
func NewMockListingRepository(ctrl *gomock.Controller) *MockListingRepository {
	mock := &MockListingRepository{ctrl: ctrl}
	mock.recorder = &MockListingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListingRepository) EXPECT() *MockListingRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockListingRepository) GetByID(ctx context.Context, id string) (entity.Listing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.Listing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockListingRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockListingRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockListingRepository) List(ctx context.Context) ([]entity.Listing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]entity.Listing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockListingRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockListingRepository)(nil).List), ctx)
}
