// Code generated by MockGen. DO NOT EDIT.
// Source: example.com/dana/module/product/internal/repository (interfaces: PropertyRepository)
//
// Generated by this command:
//
//	mockgen -destination=mock/property_repository.go -package=mock example.com/dana/module/product/internal/repository PropertyRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "example.com/dana/module/product/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockPropertyRepository is a mock of PropertyRepository interface.
type MockPropertyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPropertyRepositoryMockRecorder
	isgomock struct{}
}

// MockPropertyRepositoryMockRecorder is the mock recorder for MockPropertyRepository.
type MockPropertyRepositoryMockRecorder struct {
	mock *MockPropertyRepository
}

// NewMockPropertyRepository creates a new mock instance.
func NewMockPropertyRepository(ctrl *gomock.Controller) *MockPropertyRepository {
	mock := &MockPropertyRepository{ctrl: ctrl}
	mock.recorder = &MockPropertyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPropertyRepository) EXPECT() *MockPropertyRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockPropertyRepository) GetByID(ctx context.Context, id string) (entity.Property, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.Property)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPropertyRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPropertyRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockPropertyRepository) List(ctx context.Context, payload entity.ListPayload) ([]entity.Property, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, payload)
	ret0, _ := ret[0].([]entity.Property)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPropertyRepositoryMockRecorder) List(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPropertyRepository)(nil).List), ctx, payload)
}
